name: check

on: 
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1.7.1

      - uses: bluefireteam/melos-action@v3
      - run: melos format --output=none --set-exit-if-changed .
      - run: melos analyze
      - run: melos test

      - uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          lcov-file: ./coverage/lcov.info